- name: Install python 3.9.6
  hosts:
    - all
  gather_facts: false
  vars_files:
    - constants/urls.yml
    - constants/aws.yml
 
  pre_tasks:
  
    - name: upgrade all packages
      ansible.builtin.yum: name=* state=latest 
           
    - name: Installs a list of packages 
      ansible.builtin.yum:
        name:
          - gcc
          - openssl
          - bzip2-devel 
          - libffi-devel 
          - zlib-devel

    - name: Create directories
      ansible.builtin.file:
        path: "{{ download_dir }}"
        state: directory
        owner: "{{ aws_user }}"
        group: "{{ aws_user }}"
        mode: 488         
 
  tasks:
  
    - name: Find out if python 3.9 is installed
      ansible.builtin.stat:
        path: "/usr/local/bin/{{ python_exec }}"
      register: python_data       

    - name: Download python archive
      ansible.builtin.get_url:
        url: "{{ python_download_url }}"
        dest: "{{ download_dir }}"
        owner: "{{ aws_user }}"
        group: "{{ aws_user }}"
      when: not python_data.stat.exists   
        
    - name: Unarchive python
      ansible.builtin.unarchive:
        src: "{{ download_dir }}/{{ python_version }}.tgz"
        dest: "{{ download_dir }}"
        remote_src: true
      when: not python_data.stat.exists
        
    - name: Initialize python
      ansible.builtin.shell: "cd {{ download_dir }}/{{ python_version }}  && ./configure --enable-optimizations"
      when: not python_data.stat.exists
       
    - name: Make python
      ansible.builtin.shell: "cd {{ download_dir }}/{{ python_version }}  && make"
      when: not python_data.stat.exists
      
    - name: Build python
      ansible.builtin.shell: "cd {{ download_dir }}/{{ python_version }}  && make altinstall"
      when: not python_data.stat.exists
             
    - name: Create python virtualenv
      pip:
        name:
          - pip
        state: latest
        virtualenv: "{{ venv_path }}"
        virtualenv_command: "/usr/local/bin/{{ python_exec }} -m venv"      
 
    - name: Verify python version
      ansible.builtin.shell: "cd {{ venv_path }} && source bin/activate && python -V"   
      register: python_version
      
    - debug:
        var: python_version.stdout_lines[0]
        
    - name: Verify pip version
      ansible.builtin.shell: "cd {{ venv_path }} && source ./bin/activate && pip -V"   
      register: pip_version
      
    - debug:
        var: pip_version.stdout_lines[0]
        