- name: Install Openssl 1.1.1
  hosts:
    - all

  gather_facts: false
  vars_files:
    - constants/urls.yml
    - constants/instance.yml
 
  pre_tasks:
  
    - name: Upgrade all packages
      ansible.builtin.yum: name=* state=latest 
           
    - name: Install a list of packages 
      ansible.builtin.yum:
        name:
          - gcc 
          - perl-core 
          
    - name: Create download directory
      ansible.builtin.file:
        path: "{{ download_dir }}"
        state: directory
        owner: "{{ aws_user }}"
        group: "{{ aws_user }}"
        mode: 488         
 
  tasks:
  
    - name: Remove old openssl
      ansible.builtin.shell: "yum remove -y openssl"
  
    - name: Download openssl archive
      ansible.builtin.get_url:
        url: "{{ openssl_download_url }}"
        dest: "{{ download_dir }}"
        owner: "{{ aws_user }}"
        group: "{{ aws_user }}" 
        
    - name: Unarchive openssl
      ansible.builtin.unarchive:
        src: "{{ download_dir }}/{{ openssl_archive }}"
        dest: "{{ download_dir }}"
        remote_src: true
      
    - name: Initialize openssl
      ansible.builtin.shell: "cd {{ download_dir }}/{{ openssl_archive_nm }} && ./config --prefix={{ openssl_dir }} --openssldir={{ openssl_dir }}"
      
    - name: Build openssl
      ansible.builtin.shell: "cd {{ download_dir }}/{{ openssl_archive_nm }} && make clean && make depend && make"
      
    - name: Test openssl
      ansible.builtin.shell: "cd {{ download_dir }}/{{ openssl_archive_nm }} && make test"  
      
    - name: Install openssl
      ansible.builtin.shell: "cd {{ download_dir }}/{{ openssl_archive_nm }} && make install"   
      
    - name: Configure openssl
      ansible.builtin.shell: "sh -c 'echo /opt/openssl/lib/' > /etc/ld.so.conf.d/openssl-1.1.1t.conf"
       
    - name: Run ldconfig
      ansible.builtin.shell: "ldconfig"        
      
    - name: Edit PATH
      ansible.builtin.lineinfile:
        path: /home/{{ aws_user }}/.bash_profile
        insertbefore: '^export PATH'
        line: "PATH=$PATH:{{ openssl_dir }}/bin"
        state: present
        
    - name: Openssl version
      ansible.builtin.shell: "source /home/{{ aws_user }}/.bash_profile && openssl version"    
      register: openssl
                
    - ansible.builtin.assert: 
        that: 
          - "'{{ openssl_version }}' in '{{ openssl.stdout }}'"
              
  post_tasks:
  
    - name: Delete download directory
      ansible.builtin.file:
        path: "{{ download_dir }}"
        state: absent                 