- name: Install Openssl 1.1.1
  hosts:
    - all

  gather_facts: false
  vars_files:
    - constants/aws.yml
 
  pre_tasks:
  
    - name: Upgrade all packages
      ansible.builtin.yum: name=* state=latest 
           
    - name: Install a list of packages 
      ansible.builtin.yum:
        name:
          - gcc 
          - perl-core 
          
    - name: Create download directory
      ansible.builtin.file:
        path: "{{ aws.instance.download_dir }}"
        state: directory
        owner: "{{ aws.instance.user }}"
        group: "{{ aws.instance.user }}"
        mode: 488         
 
  tasks:
  
    - name: Remove old openssl
      ansible.builtin.shell: "yum remove -y openssl"
  
    - name: Download openssl archive
      ansible.builtin.get_url:
        url: "{{ openssl.download_url }}"
        dest: "{{ aws.instance.download_dir }}"
        owner: "{{ aws.instance.user }}"
        group: "{{ aws.instance.user }}" 
        
    - name: Unarchive openssl
      ansible.builtin.unarchive:
        src: "{{ aws.instance.download_dir }}/{{ openssl.archive }}"
        dest: "{{ aws.instance.download_dir }}"
        remote_src: true
      
    - name: Initialize openssl
      ansible.builtin.shell: "cd {{ aws.instance.download_dir }}/{{ openssl.archive_nm }} && ./config --prefix={{ openssl.dir }} --openssldir={{ openssl.dir }}"
      
    - name: Build openssl
      ansible.builtin.shell: "cd {{ aws.instance.download_dir }}/{{ openssl.archive_nm }} && make clean && make depend && make"
      
    - name: Test openssl
      ansible.builtin.shell: "cd {{ aws.instance.download_dir }}/{{ openssl.archive_nm }} && make test"  
      
    - name: Install openssl
      ansible.builtin.shell: "cd {{ aws.instance.download_dir }}/{{ openssl.archive_nm }} && make install"   
      
    - name: Configure openssl
      ansible.builtin.shell: "sh -c 'echo /opt/openssl/lib/' > /etc/ld.so.conf.d/openssl-1.1.1t.conf"
       
    - name: Run ldconfig
      ansible.builtin.shell: "ldconfig"        
      
    - name: Edit PATH
      ansible.builtin.lineinfile:
        path: /home/{{ aws.instance.user }}/.bash_profile
        insertbefore: '^export PATH'
        line: "PATH=$PATH:{{ openssl.dir }}/bin"
        state: present
        
    - name: Openssl version
      ansible.builtin.shell: "source /home/{{ aws.instance.user }}/.bash_profile && openssl version"    
      register: openssl_ver
                
    - ansible.builtin.assert: 
        that: 
          - "'{{ openssl.version }}' in '{{ openssl_ver.stdout }}'"
              
  post_tasks:
  
    - name: Delete download directory
      ansible.builtin.file:
        path: "{{ aws.instance.download_dir }}"
        state: absent                 