- name: Install python 3.11.2
  hosts:
    - all

  gather_facts: false
  vars_files:
    - constants/urls.yml
    - constants/instance.yml
 
  pre_tasks:
  
    - name: upgrade all packages
      ansible.builtin.yum: name=* state=latest 
           
    - name: Installs a list of packages 
      ansible.builtin.yum:
        name:
          - gcc
          - perl-core
          - pcre-devel
          - bzip2-devel 
          - libffi-devel 
          - zlib-devel
          - sqlite-devel
          - readline-devel
          - gdbm-devel
          - uuid-devel          
          - xz-devel 
          - ncurses-devel 
          - tk-devel 
          - db4-devel 
          - libpcap-devel 
          - expat-devel
          - tkinter 
          - lzma 
          
    - name: Create download directory
      ansible.builtin.file:
        path: "{{ download_dir }}"
        state: directory
        owner: "{{ aws_user }}"
        group: "{{ aws_user }}"
        mode: 488         
 
  tasks:
  
    - name: Download python archive
      ansible.builtin.get_url:
        url: "{{ python_download_url }}"
        dest: "{{ download_dir }}"
        owner: "{{ aws_user }}"
        group: "{{ aws_user }}" 
        
    - name: Unarchive python
      ansible.builtin.unarchive:
        src: "{{ download_dir }}/{{ python_archive }}"
        dest: "{{ download_dir }}"
        remote_src: true
            
    - name: Initialize python
      ansible.builtin.shell: "export LD_RUN_PATH={{ openssl_dir }}/lib && cd {{ download_dir }}/{{ python_archive_nm }} && ./configure --enable-optimizations --with-openssl={{ openssl_dir }} -C"
      
    - name: Make python
      ansible.builtin.shell: "cd {{ download_dir }}/{{ python_archive_nm }} && make clean && make"
      
    - name: Build python
      ansible.builtin.shell: "cd {{ download_dir }}/{{ python_archive_nm }} && make altinstall"
      
    - name: Create virtualenv
      ansible.builtin.pip:
        name:
          - pip
        state: latest
        virtualenv: "{{ venv_path }}"
        virtualenv_command: "{{ python_dir }}/{{ python_exec }} -m venv"   

  post_tasks:
  
    - name: Delete download directory
      ansible.builtin.file:
        path: "{{ download_dir }}"
        state: absent        