- name: Install python 3.11.2
  hosts:
    - all

  gather_facts: false
  vars_files:
    - constants/aws.yml
    - constants/controller.yml
 
  pre_tasks:
      
    - name: 'Controller host configuration'
      ansible.builtin.debug:
        msg:
        - "domain: {{ aws_instance_dns_domain }}"
        - "ssh port: {{ ansible_port }}"
        - "ssh user: {{ ansible_user }}"
        - "ssh key: {{ ansible_private_key_file }}"
  
    - name: Upgrade all packages
      ansible.builtin.yum: name=* state=latest 
           
    - name: Installs a list of packages 
      ansible.builtin.yum:
        name:
          - gcc
          - perl-core
          - pcre-devel
          - bzip2-devel 
          - libffi-devel 
          - zlib-devel
          - sqlite-devel
          - readline-devel
          - gdbm-devel
          - uuid-devel          
          - xz-devel 
          - ncurses-devel 
          - tk-devel 
          - db4-devel 
          - libpcap-devel 
          - expat-devel
          - tkinter 
          - lzma 
          
    - name: Create download directory
      ansible.builtin.file:
        path: "{{ aws.instance.download.path }}"
        state: directory
        owner: "{{ aws.instance.user }}"
        group: "{{ aws.instance.user }}"
        mode: 488         
 
  tasks:
  
    - name: Download python archive
      ansible.builtin.get_url:
        url: "{{ python.download.url }}"
        dest: "{{ aws.instance.download.path }}"
        owner: "{{ aws.instance.user }}"
        group: "{{ aws.instance.user }}" 
        
    - name: Unarchive python
      ansible.builtin.unarchive:
        src: "{{ aws.instance.download.path }}/{{ python.archive.name }}"
        dest: "{{ aws.instance.download.path }}"
        remote_src: true
            
    - name: Initialize python
      ansible.builtin.shell: "export LD_RUN_PATH={{ openssl.path }}/lib && cd {{ aws.instance.download.path }}/{{ python.archive.directory }} && ./configure --enable-optimizations --with-openssl={{ openssl.path }} -C"
      
    - name: Make python
      ansible.builtin.shell: "cd {{ aws.instance.download.path }}/{{ python.archive.directory }} && make clean && make"
      
    - name: Build python
      ansible.builtin.shell: "cd {{ aws.instance.download.path }}/{{ python.archive.directory }} && make altinstall"
      
  post_tasks:
  
    - name: Delete download directory
      ansible.builtin.file:
        path: "{{ aws.instance.download.path }}"
        state: absent        